version: "2"

services:
  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  web:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.prod
    restart: always
    container_name: audio_server
    command: python manage.py runserver 0.0.0.0:8000
    # volumes:
    #   - .:/code
    environment:
      - MODE_ENV=production
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
